# #+title: Author's Resume
#+options: author:t email:t creator:t toc:nil num:nil title:nil
#+date: \today
#+author: Aditya Singhania
#+email: aditya.singhania@u.yale-nus.edu.sg
#+mobile: (+65) 8840-3384
#+linkedin: adisinghania
#+github: adisidev
# #+creator: Me
# #+anon: t

* Education
** Yale-NUS College, Singapore
:PROPERTIES:
:LOCATION: Aug 2020 - May 2024
:END:
BSc. (CAP: 4.83/5.00) | Major: Mathematical, Computational, and Statistical Sciences | S$82,000 Yale-NUS Merit Scholarship

*** Yale University (Y-VISP), New Haven, Connecticut
:PROPERTIES:
:FROM: <2023-01-01>
:TO: <2023-05-01>
:END:

** Modern School Vasant Vihar, New Delhi, India
:PROPERTIES:
:LOCATION: Aug 2004 - Mar 2019
:END:

Central Board of Secondary Education | ACT: 35/36 | Graduated with a 100% in Computer Science and an overall average of 96.25%.

* Experience
*** IT Support Assistant
:PROPERTIES:
:FROM: <2020-08-01>
:TO: <2022-12-01>
:END:
-	Troubleshooted more than 1200 support tickets from close to 500 different users.
- Provided face-to-face support and technology advice to a diverse user base, helping non-tech-savvy individuals understand and utilize complex technical products effectively.
- Cultivated a friendly and welcoming environment, often being the first point of contact for users seeking guidance and support.
- Managed and maintained 100+ Mac devices, including software installations, troubleshooting, and simple hardware repairs.

** Singapore Institute of Technology
:PROPERTIES:
:LOCATION: Singapore
:END:
*** Research Assistant to Associate Professor Michael Gastner
:PROPERTIES:
:FROM: <2023-07-01>
:END:
- Implemented code to generate dynamic visuals enhancing academic presentations, debugging efficiency and external contributions.
- Produced key research materials, including scholarly writing, explainer-videos for human-subject experiments and vital production code.
- Assisted in preparing, refining, and presenting code-based research findings at two international conferences.
** Synthesis Creative Data House
:PROPERTIES:
:LOCATION: Singapore
:END:
*** Software Engineering x Data Science Intern
:PROPERTIES:
:FROM: <2023-05-01>
:TO: <2023-08-01>
:END:
- Sped up web post scrapers for various social media platforms by up to 20x by intercepting network calls, and making them async.
- Automated data workflows using Google Cloud Platform and migrated local workflows to Cloud Scheduler, Cloud Functions, and Cloud Run.
- Collaborated with Consultants, Strategists and Data Scientists to optimize data workflows for client-facing dashboards.
** Paytm
:PROPERTIES:
:LOCATION: New Delhi, India
:END:
*** DevOps Intern
:PROPERTIES:
:FROM: <2022-06-01>
:TO: <2022-08-01>
:END:
- Created ansible roles, bash scripts and cron jobs to automate tasks on production server.
- Imported existing AWS infrastructure to terraform by using terraformer to "reverse-terraform,” allowing faster deployment.
- Automated deployment process with Jenkins pipelines written in Groovy, and created tests to pass before pushing to prod.
** Yale-NUS College
:PROPERTIES:
:LOCATION: Singapore
:END:
*** C++ Developer, Research Assistant to Asisstant Professor Michael Gastner
:PROPERTIES:
:FROM: <2020-09-01>
:TO: <2022-12-01>
:END:
-	Refactored a C codebase for generating cartograms into C++, improving run time and fixing errors.
-	Automated testing using shell scripts triggered with watchexec upon build, and GitHub actions.
-	Simplified build system by moving from a plain Makefile to using CMake, allowing easy cross-platform builds.
-	Migrated codebase to object-based model, making future development much easier.
-	Sped up project by creating and managing agile workflow; code reviewed pull requests from various developers.
*** Optimization Engineer, Research Assistant to Professor Emanuel Mayer
:PROPERTIES:
:FROM: <2022-02-01>
:END:
-	Upgraded key MATLAB infrastructure without prior experience, reduced runtime from one week on server to 20 minutes on laptop.
-	Initiated C++ project on planarization of bipartite graphs (listed as project “autograph” below).
*** Peer Tutor: Introduction to Computer Science
:PROPERTIES:
:FROM: <2022-08-01>
:TO: <2022-12-01>
:END:
- Facilitated 8+ hrs/week of tutoring to provide academic support and mentorship for Introduction to Computer Science course held in OCaml.
* Additional Information
- *Technical Skills*: C/C++ (CMake, Boost, CGAL), Python, OCaml, MATLAB, R (tidyverse), SQL, Shell Scripting, Data Visualisation, Git, Docker, Emacs/Vim (Spacemacs), Terraform, Google Cloud Platform, Amazon Web Services, types upto 160 WPM
# - *Languages*: English, Hindi, Nepali
# Lymphoma/leukaemia cancer survivor passionate about helping people, I’ve connected with over 20 cancer patients one-to-one to provide emotional support.
* Publications and Conferences
- 19th International Conference on Geoinformation and Cartography (Zagreb, Croatia | Sep 2023)
- 10th International Congress on Industrial and Applied Mathematics (Tokyo, Japan | Aug 2023)
- Gastner, M.T., Miaji, N.Z. & *Singhania, A.* (2022). Smooth Pycnophylactic Interpolation Produced by Density-Equalising Map Projections. Kartografija i geoinformacije, 21 (37), 60-68. https://doi.org/10.32909/kg.21.37.3
